### ISSUE TITLE
Discuss 2 Wheatstone Bridge Circuit

### ISSUE THREAD

**Issue by kmc97** [Duke-BME-Design/Ureter#1]

**Comment by yashasaxena** [comment]
Hi Dr. Palmeri @mlp6 ,

After our final presentation, you made a suggestion about coupling our wheatstone bridge circuit with another wheatstone bridge that could cancel out the noise coming from the catheter with readings from another pressure catheter? After three weeks, we kind of forgot the specifics of your suggestion and were hoping you could clarify! Deepti and I will be working on denoising and amplifying the signal for the next week or so, so would be great to get your two cents. I attached images of our circuit and initial Pressure-Voltage readings. We have not connected the low pass filter yet. 

<img width="710" alt="screen shot 2018-01-17 at 10 02 44 am" src="https://user-images.githubusercontent.com/8584289/35049337-a7340f0e-fb6d-11e7-9427-e7b2b93c9b09.png">

<img width="1126" alt="screen shot 2018-01-17 at 10 04 34 am" src="https://user-images.githubusercontent.com/8584289/35049397-e027ad66-fb6d-11e7-8f56-f558e67e973b.png">

**Comment by mlp6** [comment]
Hmmmm... I remember us briefly discussing this during your presentation, but I have forgotten exactly what I said / was referring to.  I think that instead of having a second Wheatstone bridge, you want to try to introduce some noise-cancelling elements into your existing bridge.  We can discuss during our scrum this week.

**Comment by yashasaxena** [comment]
discussed
