### ISSUE TITLE
2nd filtering stage and Dynamic range of 0-4 V

### ISSUE THREAD

**Issue by kmc97** [Duke-BME-Design/Ureter#9]
play with cut off frequencies
Goal: dynamic range of 0-4 V

**Comment by deeptig94** [comment]
- Implemented 2nd filtering stage, but observed excessive delay in output (more than 20 s from change in input to change in output). Since there is already a delay from the catheter (most likely caused by charging and discharging of capacitor), we decided to remove this stage to prevent added error.
- Attempted to get a voltage range of 0-4V using multiple voltage offset (summing amp) and amplification stages. Due to some kind of drift, though the range is usually 0-4V, sometimes the voltage increases decreases so that it is no longer in that range.
